services:
  etcd:
    image: bitnami/etcd:3.5
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"

  apisix:
    image: docker.io/apache/apisix:3.13.0-ubuntu
    container_name: apisix
    depends_on:
      - etcd
    ports:
      - "9080:9080"  # proxy
      - "9443:9443"  # proxy https
      - "9180:9180"  # admin api
    environment:
      APISIX_STAND_ALONE: "false"
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
#
#  apisix-dashboard:
#    image: apache/apisix-dashboard:3.0.1-alpine
#    container_name: apisix-dashboard
#    depends_on:
#      - apisix
#    ports:
#      - "9000:9000"
#    volumes:
#      - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
#    restart: unless-stopped
